# Text Classification

In [1]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer,TfidfVectorizer
from sklearn.pipeline import Pipeline 

C:\Users\dhawa\.conda\envs\nlp_course\lib\site-packages\sklearn\utils\validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'


In [3]:
df = pd.read_csv('../Resources/UPDATED_NLP_COURSE/TextFiles/smsspamcollection.tsv',sep='\t')

In [4]:
df.head()

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2

In [5]:
df.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [6]:
len(df)

5572

In [8]:
df['label'].unique()

array(['ham', 'spam'], dtype=object)

In [9]:
df['label'].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [16]:
import matplotlib.pyplot as plt
plt.hist(df[df['label']=='ham']['length'])
plt.show()

In [19]:
import sklearn
from sklearn import model_selection
from sklearn.model_selection import train_test_split

In [20]:
# Feature Data
X=df[['length','punct']]
# Label data
y=df['label']

X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.3)

In [21]:
X_train.shape

(3900, 2)

In [22]:
X_test.shape

(1672, 2)

In [23]:
Y_train.shape

(3900,)

In [24]:
Y_test.shape

(1672,)

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
lr_model=LogisticRegression(solver='lbfgs')

In [27]:
lr_model.fit(X_train,Y_train)

C:\Users\dhawa\.conda\envs\nlp_course\lib\site-packages\sklearn\utils\fixes.py:357: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [ ]:
lr_model.predict()

In [30]:
from sklearn import metrics

In [29]:
predictions=lr_model.predict(X_test)

In [31]:
metrics.accuracy_score(predictions,Y_test)

0.8534688995215312

In [34]:
print(metrics.confusion_matrix(predictions,Y_test))

[[1426  221]
 [  24    1]]


In [35]:
from sklearn.naive_bayes import MultinomialNB

nb_model=MultinomialNB()

nb_model.fit(X_train,Y_train)

predictions=nb_model.predict(X_test)

In [36]:
metrics.accuracy_score(predictions,Y_test)

0.8654306220095693

In [38]:
print(metrics.confusion_matrix(predictions,Y_test))

[[1445  220]
 [   5    2]]


In [43]:
from sklearn.svm import SVC
svc_model=SVC()

svc_model.fit(X_train,Y_train)

predictions=svc_model.predict(X_test)

C:\Users\dhawa\.conda\envs\nlp_course\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [44]:
metrics.accuracy_score(predictions,Y_test)

0.8893540669856459

In [45]:
print(metrics.confusion_matrix(predictions,Y_test))

[[1393  128]
 [  57   94]]
